/* -*- Mode: C; tab-width: 8; indent-tabs-mode: t; c-basic-offset: 8 -*- */

#ifndef __E_MESSENGER_TYPES_H__
#define __E_MESSENGER_TYPES_H__

#include <libgnome/gnome-defs.h>

BEGIN_GNOME_DECLS

typedef enum {
	E_MESSENGER_SIGNON_ERROR_NONE,
	E_MESSENGER_SIGNON_ERROR_NET_FAILURE,
	E_MESSENGER_SIGNON_ERROR_INVALID_LOGIN,
	E_MESSENGER_SIGNON_ERROR_PMS_FAILURE,
	E_MESSENGER_SIGNON_ERROR_DEFUNCT_CONNECTION,
	E_MESSENGER_SIGNON_ERROR_UNKNOWN_FAILURE
} EMessengerSignonError;

typedef enum {
	E_MESSENGER_USER_STATUS_ONLINE,
	E_MESSENGER_USER_STATUS_IDLE,
	E_MESSENGER_USER_STATUS_AWAY,
	E_MESSENGER_USER_STATUS_NOT_AVAILABLE,
	E_MESSENGER_USER_STATUS_OCCUPIED,
	E_MESSENGER_USER_STATUS_INVISIBLE,
	E_MESSENGER_USER_STATUS_FREE_CHAT
} EMessengerUserStatus;

const char *e_messenger_signon_error_to_string (const EMessengerSignonError signon_error);

END_GNOME_DECLS

#endif /* ! __E_MESSENGER_TYPES_H__ */
